

const snapshot = [
    {
        type:"mountain",
        img:"https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497739/m1_qz9kuw.jpg",
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498004/m11_s066vg.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497991/m10_i9cve4.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497981/m9_xadbhs.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497946/m7_w9zzei.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497936/m6_eaq6zf.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497926/m5_dqiaah.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497902/m4_hktnlz.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497891/m3_oxqjbm.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682497864/m2_wbccjh.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498306/images_biqabo.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498281/images_ps8ar2.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498256/images_gulgct.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498244/images_zrxr9z.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498221/images_xskfij.jpg',
    },
    {
        type:"mountain",
        img:'https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498205/images_pbdrnd.jpg',
    },
]
 export default snapshot