const snapshot = [
  {
    id: 1,
    type: "mountain",
    title:'Mount Kilimanjaro',
    description:"Mount Kilimanjaro is a dormant volcano located in Kilimanjaro Region of Tanzania. It has three volcanic cones: Kibo, Mawenzi, and Shira.",
    height:5895,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683391192/lucky/Mountain/Mount%20Kilimanjaro.jpg",
  },
  {
    id: 2,
    type: "mountain",
    title:"Mount Ras Dashen",
    description:'Also known as Ras Dejen, is the highest mountain in Ethiopia and fourteenth highest peak in Africa. Located in the Simien Mountains National Park in the North Gondar Zone of the Amhara Region',
    height:4550,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683391469/lucky/Mountain/Mount%20Ras%20Dashen.jpg",
  },
  {
    id: 3,
    type: "mountain",
    title:'Mount Stanley',
    description:'Mount Stanley or Mount Ngaliema is a mountain located in the Rwenzori range.It is the highest mountain of both the Democratic Republic of the Congo and Uganda, and the third highest in Africa, after Kilimanjaro and Mount Kenya',
    height:5109,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683391617/lucky/Mountain/Mount%20Stanley.jpg",
  },
 
  {
    id: 4,
    type: "mountain",
    title:'Mount Meru',
    description:'Mount Meru is a dormant stratovolcano located 70 kilometres west of Mount Kilimanjaro in southeast Arusha Region, Tanzania. It is visible from Mount Kilimanjaro on a clear day, and is the fifth-highest of the highest mountain peaks of Africa, dependent on definition',
    height:4562.13,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683480041/lucky/Mountain/jgj1moatnjn3yed9ba4p.jpg",
  },
  {
    id: 5,
    type: "mountain",
    title:'Mount Karisimbi',
    description:'Mount Karisimbi is an active stratovolcano in the Virunga Mountains on the border between Rwanda and the Democratic Republic of Congo. It is the highest of the eight major mountains of the mountain range, which is a part of Albertine Rift, the western branch of the East African Rift.',
    height:4507,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683394881/lucky/Mountain/Mount%20Karisimbi.jpg",
  },
  {
    id: 6,
    type: "mountain",
    title:'Mount Elgon',
    description:'Mount Elgon is an extinct shield volcano on the border of Uganda and Kenya, north of Kisumu and west of Kitale. The mountain\'s highest point, named "Wagagai", is located entirely within Uganda.',
    height:4321,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683455725/hnojm4svb7t7qcvkctco.jpg",
  },
  {
    id: 7,
    type: "mountain",
    title:'Mount Toubkal',
    description:'Toubkal or Tubkal is a mountain peak in southwestern Morocco, located in the Toubkal National Park. It is the highest peak in the Atlas Mountains, Morocco, North Africa and the Arab-Speaking World.',
    height:4167,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683395188/lucky/Mountain/Mount%20Toubkal.jpg",
  },
  {
    id: 8,
    type: "mountain",
    title:'Mount Thabana Ntlenyana',
    description:'Thabana Ntlenyana is the highest mountain in southern Africa, located in the Drakensberg mountain range. The name means "beautiful little mountain" in the Sesotho language.',
    height:3462,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683480125/lucky/Mountain/dyzks7r7clqwhhxp2aox.jpg",
  },
  {
    id: 9,
    type: "mountain",
    title:'Mount Tullu Dimtu',
    description:'Tullu Dimtu is the fourth highest peak in Ethiopia after Ras Dashen, Ancua, and Kidus Yared. Tullu Dimtu is on the Sanetti Plateau in the Bale Mountains of Oromia Region in southeast Ethiopia, within Bale Mountains National Park. It forms part of the divide between the drainage basins of the Weyib and Shebelle Rivers',
    height:4389,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683467350/wxworpdd5oggghbfa3iw.jpg",
  },
  {
    id: 10,
    type: "mountain",
    title:'Mount Kidus Yared',
    description:'Mount Kidus Yared is home to several communities and settlements who cultivate the land. These settlements form part of the landscape of Kidis Yared and have become somewhat of an attraction for hikers.',
    height:4453,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683480227/lucky/Mountain/orecc3mwodezwyle0jmy.jpg",
  },
  {
    id:11,
    type: "mountain",
    title:'Mount Gurage',
    description:'Mount Gurage or Zebidar terraria is a mountain located in central Ethiopia. It is the highest point in both the Gurage Zone and the entire Southern Nations, Nationalities, and Peoples\' Region.',
    height:3700,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1682498281/images_ps8ar2.jpg",
  },

  {
    id:12,
    type: "mountain",
    title:'Mount Satima',
    description:'Mount Satima, also known as Mount Lesatima and often abbreviated to Satima or Lesatima, is the third-highest mountain in Kenya and the highest in the Aberdare Range. The Maasai name is Oldoinyo Lesatima, which has a variety of alternative spellings, such as Ol Donyo Le Satima, and means "mountain of the bull calf',
    height:4001,
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683480429/lucky/Mountain/qvygmetiohucmdbfu9mt.jpg",
  },
  {
    id:13,
    type: "beach",
    title:'Sharm el-Sheikh',
    description:'Sharm el-Sheikh has become Egypt’s resort capital for good reason: the warm, crystal waters and wide beaches are great for swimmers and sunbathers and it’s the gateway to some of the best diving in the world, along the reefs of the Red Sea',
    location:'Egypt',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683396320/lucky/Beaches/Sharm%20el-Sheikh.webp",
  },
  {
    id:14,
    type: "beach",
    title:'Diani Beach',
    description:'Diani Beach is an idyllic 20-kilometer stretch of palm-fringed beach is kept pristine and clear of seaweed by the coral reef just offshore. This coastal paradise has become one of Kenya’s most popular beaches.',
    location:'Kenya',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683396484/lucky/Beaches/Diani%20Beach.webp",
  },
  {
    id:15,
    type: "beach",
    title:'Chitimba',
    description:'There isn’t much to Chitimba besides a peaceful stretch of inland beach – the lake the beach borders is one of the biggest in Africa. Wrapped with densely vegetated hills and trees that filter down to the edge of the sand, it’s a quiet piece of freshwater paradise.If you’re feeling energetic, Chitimba Camp’s guides can take you walking into the surrounding hills.',
    location:'Malawi',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683396642/lucky/Beaches/Chitimba.webp",
  },
  {
    id:16,
    type: "beach",
    title:'Anse Soleil',
    description:'Jungle and boulders tumble down a hillside and into the small beach and bay of Anse Soleil in the southwest of Mahe. It’s peaceful, private and a very romantic beach from which to watch the sun set.',
    location:'Maye,Seychelles',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683396837/lucky/Beaches/Anse%20Soleil.webp",
  },

  {
    id:17,
    type: "beach",
    title:'Anse Source d’Argent',
    description:'It’s obvious why Anse Source d’Argent has been labeled the world’s most photographed beach. A walking trail, with jungle tumbling down a hill on one side, winds between massive granite boulders to reveal a sandy beach so perfectly white, and with water so exquisitely turquoise, it seems unreal.',
    location:'La Digue, Seychelles',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397004/lucky/Beaches/Anse%20Source%20d%E2%80%99Argent.webp",
  },
  {
    id:18,
    type: "beach",
    title:'Belle Mare',
    description:'The sunrise from the quiet beach of Belle Mare, on the east coast of Mauritius, is worth the bleary-eyed wake-up call. Although it’s known for its fine white sand, you’re likely to find a secluded space along this barely-developed stretch of beach.The water is calm and shallow; just what you want for wallowing away lazy days.',
    location:'Mauritius',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397177/lucky/Beaches/Belle%20Mare.webp",
  },
  {
    id:19,
    type: "beach",
    title:'Ifaty',
    description:'If you’ve always longed to relax on a white stretch of beach where shade is provided by lazy palm trees, not striped umbrellas, Ifaty, on the southwest coast of Madagascar, could be your answer.This stretch of coastline, lined in parts by fishermen’s houses built mostly from natural materials, is flanked by coral reef, which you can explore with goggles and a snorkel or on the surface from a colorful dugout canoe.',
    location:'Madagascar',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397314/lucky/Beaches/Ifaty.webp",
  },
  {
    id:20,
    type: "beach",
    title:'Tofo',
    description:'A sandy eight-kilometer stretch of beach with gorgeous, clear water is what you can expect from Tofo in Mozambique.It’s perfect for beach-lollers, sand-frolickers and further out to sea, divers and fishermen have good opportunities to express themselves too.',
    location:'Mozambique',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397484/lucky/Beaches/Tofo.webp",
  },
  {
    id:21,
    type: "beach",
    title:'Bazaruto',
    description:'For an idyllic tropical island beach, Bazaruto, the namesake of Bazaruto Archipelago, wins hands-down. The island’s lazy sand beaches stretch forever into clear turquoise water, before dropping off into the Indian Ocean, and palm trees dangle over the beach creating perfect cocktail-sipping shade.',
    location:'Mozambique',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397595/lucky/Beaches/Bazaruto.webp",
  },
  {
    id:22,
    type: "beach",
    title:'Uvongo',
    description:'Situated at the mouth of the Ivungu River mouth, Uvongo beach has a shallow lagoon, perfect for little ones to splash about in. Hire a pedallo and paddle to the base of the 23-meter-high waterfall that drops into the lagoon.',
    location:'South Africa',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397723/lucky/Beaches/Uvongo.webp",
  },
  {
    id:23,
    type: "beach",
    title:'Coffee Bay',
    description:'Coffee Bay on South Africa’s Wild Coast is beautifully wild. With cliffs that plummet and green hills that roll into the turbulent waters of the Indian Ocean, this is one moody beach that will take your breath away. Hole In The Wall (eight kilometers up the road from Coffee Bay) is a spectacular rock just out to sea at the mouth of the Mpako River.',
    location:'Wild Coast, South Africa',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397853/lucky/Beaches/Coffee-bay.webp",
  },
  {
    id:24,
    type: "beach",
    title:'River No. 2 Beach',
    description:'There’s a real sense of space and being in the middle of nowhere at River No. 2 Beach just outside Freetown in Sierra Leone, with its pure white sand and a backdrop of lush, vegetated mountains.',
    location:'Freetown, Sierra Leone',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683397966/lucky/Beaches/River%20No.%202%20Beach.webp",
  },
  {
    id:25,
    type: "bird",
    title:'Lilac Breasted Roller',
    discription:'The lilac-breasted roller is an African bird of the roller family, Coraciidae. It is widely distributed in Southern and Eastern Africa, and is a vagrant to the southern Arabian Peninsula. It prefers open woodland and savanna, and it is for the most part absent from treeless places',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683398332/lucky/Birds/lilac-breasted.jpg",
  },
  {
    id:26,
    type: "bird",
    title:'African fish eagle',
    discription:'Also known as the African sea eagle, is a large species of eagle found throughout sub-Saharan Africa wherever large bodies of open water with an abundant food supply occur. It is the national bird of Malawi, Namibia, Zambia, and Zimbabwe. As a result of its large range, it is known in many languages',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683398488/lucky/Birds/African_fish_eagle.jpg",
  },
  {
    id:27,
    type:'bird',
    title:'African fish eagle',
    discription:'Also known as the African sea eagle, is a large species of eagle found throughout sub-Saharan Africa wherever large bodies of open water with an abundant food supply occur. It is the national bird of Malawi, Namibia, Zambia, and Zimbabwe. As a result of its large range, it is known in many languages',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1682935184/STanager-Shapiro-ML_ctneby.jpg",
  },
  {
    id:28,
    type: "bird",
    title:'Hornbills',
    description:'Hornbills are a family of bird found in tropical and subtropical Africa, Asia and Melanesia. They are characterized by a long, down-curved bill which is frequently brightly coloured and sometimes has a casque on the upper mandible.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683398658/lucky/Birds/Great_hornbill.jpg",
  },
  {
    id:29,
    type: "bird",
    title:'Grey Crowned crane',
    description:'The grey crowned crane,or the African crowned crane, golden crested crane, golden crowned crane, East African crane, East African crowned crane, African crane, Eastern crowned crane, Kavirondo crane, South African crane and crested crane, is a bird in the crane family, Gruidae.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683398853/lucky/Birds/%20grey%20crowned%20crane.jpg",
  },
  {
    id:30,
    type: "bird",
    title:'Marabou',
    description:'The marabou stork is a large wading bird in the stork family Ciconiidae native to sub-Saharan Africa. It breeds in both wet and arid habitats, often near human habitation, especially landfill sites. ',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683398975/lucky/Birds/%20marabou.jpg",
  },
  {
    id:31,
    type: "bird",
    title:'Sunbirds',
    description:"Sunbirds and spiderhunters make up the family Nectariniidae of passerine birds. They are small, slender passerines from the Old World, usually with downward-curved bills. Many are brightly coloured, often with iridescent feathers, particularly in the males. Many species also have especially long tail feathers.",
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399111/lucky/Birds/sunbirds.jpg",
  },
  {
    id:32,
    type: "bird",
    title:'Bushshrikes',
    description:'The bushshrikes are smallish passerine birds. They were formerly classed with the true shrikes in the family Laniidae, but are now considered sufficiently distinctive to be separated from that group as the family Malaconotidae, a name that alludes to their fluffy back and rump feathers.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399244/lucky/Birds/Flickr_-_Rainbirder_-_Yellow-crowned_Gonolek__28Laniarius_barbarus_29__281_29_hg4g0f.jpg",
  },
  {
    id:33,
    type: "bird",
    title:'Hoopoes',
    description:"Hoopoes are colourful birds found across Africa, Asia, and Europe, notable for their distinctive \"crown\" of feathers. Three living and one extinct species are recognized, though for many years all of the extant species were lumped as a single species—Upupa epops.",
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399460/lucky/Birds/Hoopoes.jpg",
  },
  {
    id:34,
    type: "bird",
    title:"Southern Masked Weaver",
    description:'The southern masked weaver, or African masked weaver, is a resident breeding bird species common throughout southern Africa. This weaver is very widespread and found in a wide range of habitats, including shrubland, savanna, grassland, open woodland, inland wetlands and semi-desert areas.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399619/lucky/Birds/southern%20masked%20weaver.jpg",
  },
  {
    id:35,
    type: "bird",
    title:'Honeyguides',
    description:'Honeyguides are near passerine birds in the order Piciformes. They are also known as indicator birds, or honey birds, although the latter term is also used more narrowly to refer to species of the genus Prodotiscus.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399723/lucky/Birds/Honeyguide.jpg",
  },
  {
    id:36,
    type: "bird",
    title:'African Jacana',
    description:'The African jacana is a wader in the family Jacanidae. It has long toes and long claws that enables it to walk on floating vegetation in shallow lakes, its preferred habitat. It is widely distributed in sub-Saharan Africa.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683399846/lucky/Birds/Jacana.jpg",
  },
  {
    id:37,
    type: "food",
    title:'Tibs',
    description:'Sliced beef or lamb, pan-fried in butter, garlic and onion, tibs is one of the most popular dishes among Ethiopians. It comes in a variety of forms, varying in type, size or shape of the cuts of meat used, and can range from hot to mild or contain little to no vegetables.',
    location:"Ethiopia",
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400065/lucky/Food/Tibs.webp",
  },
  {
    id:38,
    type: "food",
    title:'Kitfo',
    description:'Made from the leanest meat, kitfo is viewed as a big treat by ordinary Ethiopians, while its nutritional powers are also praised.Similar to French steak tartare, the meat is minced and warmed in a pan with a little butter, mitmita (a stronger version of berbere) and sometimes thyme. ',
    location:"Ethiopia",
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400361/lucky/Food/Kitfo.jpg",
  },
  {
    id:39,
    type: "food",
    title:'Beyainatu',
    description:'The name of Ethiopia’s most popular vegetarian dish translates as “a bit of every type,” hence your injera arrives blanketed in piles of tasty and colorful vegetables, potatoes, curries, lentil stews and more, creating a riot of colors and tastes. ',
    location:"Ethiopia",
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400464/lucky/Food/Beyainatu.jpg",
  },
  {
    id:40,
    type: "food",
    title:'Bobotie',
    description:'Bobotie is a delicious minced meat spiced with medium-hot curry, turmeric, garlic, lemon zest, onions, herbs, salt, and pepper. Many people like to add raisins. Once baked until fully cooked, the dish is topped with an egg and milk mixture and placed back into the oven to set.',
    location:'South Africa',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400737/lucky/Food/Bobotie-1-960x960.jpg_nlimsz.webp",
  },
  {
    id:41,
    type: "food",
    title:'Biltong and Droewors',
    description:'Biltong and Droëwors are cured meat consumed as tasty snacks. This local delicacy is culturally associated with watching rugby, cricket, and football (soccer), the most popular sports in the country, or while traveling on long road trips.',
    location:'South Africa',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400850/lucky/Food/Biltong-and-Droewors-.jpg_ds1llg.webp",
  },
  {
    id:42,
    type: "food",
    title:'Potjiekos',
    description:'Potjiekos translates literally as “food made in a pot”. Of course, any stew recipe works well, but the traditional method is to layer fresh vegetables on top of meat with a little sauce—the cast-iron pot cooks on low heat, usually outside on a small fire. Control of fire heat is an art that most indigenous South Africans learned from an early age.',
    location:'South Africa',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683400956/lucky/Food/Potjiekos--960x640.jpg_jfoien.webp",
  },
  {
    id:43,
    type: "food",
    title:'Foul Mudammas/Medames and Taameya',
    description:'Foul Medames is a slow-cooked fava beans stew. It is the most popular breakfast food in Egypt in most families. Foul Medames can be served as whole beans or mashed. The most common toppings added to it include cumin, lemon, oil, pepper, salt, parsley, onion, and butter.',
    location:'Egypt',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683401110/lucky/Food/egyptian-food-01a-735x459.jpg_q5blty.webp",
  },
  {
    id:44,
    type: "food",
    title:'Koshary',
    description:'Koshary is a popular local food that is made of boiled lentils, rice, macaroni, and chickpeas, along with fried onions and a special Egyptian red sauce. It is usually served with extra packs of vinegar and hot sauce, to be added to taste.',
    location:'Egypt',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683401290/lucky/Food/Koshary.webp",
  },
  {
    id:45,
    type: "food",
    title:'Kawaree',
    description:'Kawaree is a dish consisting of cow feet that are well-cleaned and boiled. The consistency is gelatinous, and it is used to make Kawaree soup.It is a dish consisting of cow feet that are well-cleaned and boiled. The consistency is gelatinous, and it is used to make Kawaree soup.',
    location:'Egypt',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1682935492/170410115312-african-food-jollof-rice_azmphp.jpg",
  },
  {
    id:46,
    type: "food",
    title:'Jollof Rice',
    description:'Jollof rice is a popular dish eaten in West African countries such as Nigeria, Ghana, Cameroon, Liberia, Mali, Togo, Gambia, and Côte d’Ivoire.It is usually eaten with side dishes such as fried plantains, vegetable salad with cream, coleslaw, and moin moin (bean pudding), in addition to proteins such as beef, chicken, turkey, and fish.',
    location:'West Africa',
    img: "https://nomadparadise.com/wp-content/uploads/2020/08/nigerian-food-01-735x459.jpg.webp",
  },
  {
    id:47,
    type: "food",
    title:'Iyan',
    description:' iyan is a bunch of yam pieces pounded or mashed using a mortar and pestle, blender, or mixer. It can be enjoyed with various kinds of tasty stews and soups, like egusi soup (melon seed soup), or efo riro (leafy vegetable stew). The soup may be served on the same plate or on a different plate. ',
    location:'Nigeria',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683401822/lucky/Food/Iyan.webp",
  },
  {
    id:48,
    type: "food",
    title:'Suay',
    description:'Suya is a flavorful Nigerian dish from the northern part of Nigeria. It is a Hausa specialty, made by grilling pieces of skewered meat (especially beef) with salt, onions, ground peanut, pepper, and other spices.',
    img: "https://res.cloudinary.com/dvfszvcxa/image/upload/v1683401989/lucky/Food/Suay.webp",
  },

 
 
];
export default snapshot;
